export const categories = [
  "Saúde",
  "Desenvolvimento",
  "Educação",
  "Governo e Articulação Política",
  "Juventude",
  "Esporte e Lazer",
  "Meio Ambiente",
  "Planejamento",
  "Políticas públicas para as mulheres",
  "Representação em João Pessoa",
  "Superintendência Cajazeirense de Transporte e ",
  "Controladoria Geral do Município",
  "Instituto de Previdência e Assistência Social",
  "Procuradoria Geral do Município",
  "Fazenda Pública",
  "Administração",
  "Cultura e Turismo",
  "Desenvolvimento Econômico e Empreendedorismo",
  "Desenvolvimento Humano",
];
