import { AiOutlineHeart } from "react-icons/ai";
import {
  MdSchool,
  MdEco,
  MdFace,
  MdSupervisorAccount,
  MdManageHistory,
  MdPendingActions,
  MdWoman,
  MdTranscribe,
  MdEmojiTransportation,
  MdAccountBalance,
  MdAttachMoney,
  MdCurrencyExchange,
  MdOutlineBusiness,
  MdAllInbox,
  MdDirectionsBus,
  MdAddBusiness,
  MdHowToReg,
} from "react-icons/md";

export const categories = [
  { title: "Saúde", icon: AiOutlineHeart },
  { title: "Desenvolvimento", icon: MdManageHistory },
  { title: "Educação", icon: MdSchool },
  { title: "Governo e Articulação Política", icon: MdSupervisorAccount },
  { title: "Juventude, Esporte e Lazer", icon: MdFace },
  { title: "Meio Ambiente", icon: MdEco },
  { title: "Planejamento", icon: MdPendingActions },
  { title: "Políticas públicas para as mulheres", icon: MdWoman },
  { title: "Representação em João Pessoa", icon: MdTranscribe },
  {
    title: "Superintendência Cajazeirense de Transporte",
    icon: MdEmojiTransportation,
  },
  { title: "Controladoria Geral do Município", icon: MdAccountBalance },
  {
    title: "Instituto de Previdência e Assistência Social",
    icon: MdCurrencyExchange,
  },
  { title: "Procuradoria Geral do Município", icon: MdOutlineBusiness },
  { title: "Fazenda Pública", icon: MdAttachMoney },
  { title: "Administração", icon: MdAllInbox },
  { title: "Cultura e Turismo", icon: MdDirectionsBus },
  {
    title: "Desenvolvimento Econômico e Empreendedorismo",
    icon: MdAddBusiness,
  },
  { title: "Desenvolvimento Humano", icon: MdHowToReg },
];
